packetdrill: Add "a few" more tests and some "minor" changes
multipath-tcp/packetdrill_mptcp pull request #1
Opened 2022-12-02 00:29 UTC by cpaasch

Is this a code-dump? Yes! 😅

But, this is our entire MPTCP suite of packetdrill tests, together with fixes/... in the packetdrill source-code.

All of these tests are passing successfully on mptcp_v0.96.

Happy to discuss on how we can best structure this so it can be merged.

2022-12-02 16:18 UTC, matttbe requested changes
Thank you very much for sharing all this test suite, that's nice to go into that direction!

The first commits look good to me.

I quickly looked at the last one:
- I didn't check the *.pkt files: a lot (:+1:) but also hard to review :) (and if they passes, that's good)
- it is difficult to review the modifications in the .c without explanations and mixed with refactoring but I'm OK to accept that thanks to all new tests you added here!
- You also shared some shell scripts but some of them source files that have not been added here. Can you share them or adapt the scripts please? (see my comments inline)
- (it could be nice to switch to `run_all.py` from upstream :) )

When the fix with the scripts have been done, I will try to run the tests on my side and then we can merge :-)

Thanks again!

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/msg_fastopen/run_test.sh
> +source ~/high_tolerance
can you share this file as well and change the path please?

(or move the tests with a different tolerance to a different dir)

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/mp_fail/run_test.sh
> +source ~/dont_test
can you share this file and change the path please?

(or move the tests not to be tested to a different dir)

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/remove_address/run_test.sh
> +#!/bin/bash
(it would be easier to maintain symlinks if you use the exact same scripts in different dirs :) )

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/run_test.sh
> +source ~/dont_test
(same: share or move? :) + symlink if you can re-use the same script in different places)

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/sysctl_enable/run_test.sh
> +source ~/high_tolerance
(same)

2022-12-02 16:18 UTC, matttbe commented on gtests/net/packetdrill/examples/tests/run_test.sh
> +source ~/dont_test
(same)

2022-12-05 20:43 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/mp_fail/run_test.sh
> +source ~/dont_test
Yeah - let me change that... The `dont_test` file is just to cover the case where a test does not work on IPv4 or IPv6. But, there is a better way to handle this: Add
```
--ip_version=...
--mtu=...
```
to the beginning of those scripts.

I will do that.

2022-12-05 20:43 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/msg_fastopen/run_test.sh
> +source ~/high_tolerance
Let me remove the `run_test.sh` file from `msg_fastopen` directory.

2022-12-05 20:44 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/remove_address/run_test.sh
> +#!/bin/bash
Let me remove those `run_test.sh`. Nobody should be using those ;-)

2022-12-05 20:44 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/run_test.sh
> +source ~/dont_test
Delete.

2023-01-12 23:37 UTC, cpaasch commented
@matttbe - I removed the "dont_test"-thing (and annotated scripts with `--ip_version`) and removed all the run_test.sh in the sub-directories.

2023-01-13 10:02 UTC, matttbe approved these changes
It looks good to me!

I didn't run all the tests yet. I don't know if it makes sense for me to do so because I'm probably sure I will have issues with the timing stuff, not have the same kind of test machine as you but I will check if I can.

Anyway, we can already merge, not waiting for these results if you prefer.

2023-01-13 10:02 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/mp_join/mp_join-subflows_2pkt_1000.pkt
> +--ip_version=ipv4
when you will switch to the latest upstream version, you might need to rename the file to end with `_v4.pkt`: when `run_all.py` is used, it will run each test (in // and in a dedicated netns) in v4, v4-mapped-v6 and v6 except if the test file ends with `_v4.pkt` or `_v6.pkt`.

I guess it is interesting to have both `--ip_version=(...)` and `_v4.pkt`. This can of course be done later.

2023-01-13 10:02 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/mp_join/mp_join_synack_retr_02.pkt
> ++0.1 `sysctl -w net.ipv4.tcp_synack_retries=5`
FYI, I think that upstream, they started to use `../common/set_sysctls.py /proc/sys/net/(...)=(...)` at the beginning and `/tmp/sysctl_restore_${PPID}.sh` at the end.

But if I'm not mistaken, the new recommended way to exec tests is to use `run_all.py` which will run each test in a dedicated netns. Then no need to do the "reset" at the end.

On the other end, I think it is then important, for each test to have at the beginning:

    --tolerance_usecs=xxx    # especially for the slow public CIs...
    `../common/defaults.sh`  # (default sysctl values)

(of course, no need to change anything here, just FYI for later ;-) )

2023-01-13 10:02 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/run_test.sh
> +  sudo ip tcp_metrics flush all > /dev/null 2>&1
as a first step to using the new script, to imitate `run_all.py`, you could create a new netns per test here :) (and run them in parallel)

(for later if you think it might be useful)

2023-01-13 10:02 UTC, matttbe commented on gtests/net/packetdrill/ip.h
> +#define IP_ECN_MASK 7
(not sure why you modified this before but that's probably fine :) )

2023-01-13 10:03 UTC, matttbe commented
I forgot to say I added a few ideas for later. And thank you for the new version ;-)

2023-01-17 16:41 UTC, cpaasch commented
> It looks good to me!
> 
> I didn't run all the tests yet. I don't know if it makes sense for me to do so because I'm probably sure I will have issues with the timing stuff, not have the same kind of test machine as you but I will check if I can.

All tests pass for me. Regarding the timing, overall it would be good to get rid of `--tolerance_usecs` across the tests and rather use targeted ranges for those packets/events that have variance. That is in my experience the best approach.

> Anyway, we can already merge, not waiting for these results if you prefer.

Yes, good to merge IMO.

2023-01-17 16:48 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/mp_join/mp_join-subflows_2pkt_1000.pkt
> +--ip_version=ipv4
Ah! That's nice that you do it based on the suffix. Good idea.

2023-01-17 16:50 UTC, cpaasch commented on gtests/net/packetdrill/examples/mptcp/run_test.sh
> +  sudo ip tcp_metrics flush all > /dev/null 2>&1
Does the forked kernel have all the necessary sysctls namespace-ified ?

2023-01-19 10:43 UTC, matttbe commented on gtests/net/packetdrill/examples/mptcp/run_test.sh
> +  sudo ip tcp_metrics flush all > /dev/null 2>&1
not the ones related to MPTCP but for the rest, I think yes.

So the tests containing `net.mptcp.mptcp` should not be ran in // (and the reset needs to be done after).

2023-01-19 11:20 UTC, matttbe commented
> > It looks good to me!
> > I didn't run all the tests yet. I don't know if it makes sense for me to do so because I'm probably sure I will have issues with the timing stuff, not have the same kind of test machine as you but I will check if I can.
> 
> All tests pass for me. Regarding the timing, overall it would be good to get rid of `--tolerance_usecs` across the tests and rather use targeted ranges for those packets/events that have variance. That is in my experience the best approach.

When using a public CI, especially with the debug kernel config, the execution is quite/very slow.

For the moment, I don't see how we can increase the default time "globally" for the CI. Except modifying `tolerance_usecs` (or `tolerance_percent`, new option from upstream) in config.c or modifying `run_all.py`.

> > Anyway, we can already merge, not waiting for these results if you prefer.
> 
> Yes, good to merge IMO.

I wanted to do some tests before but I was not able to compile the new version, maybe because I use GCC 11?

I have a lot of warnings (`-Wunused-result`, `-Waddress-of-packed-member`, `-Wformat=`, `-Wdeprecated-declarations`, `-Wstrict-aliasing`, `-Wparentheses`, `-Wmisleading-indentation`) and then the linker fails:

```
cc -o packetdrill packetdrill.o checksum.o code.o config.o hash.o hash_map.o ip_address.o ip_prefix.o netdev.o net_utils.o packet.o packet_socket_linux.o packet_socket_pcap.o packet_checksum.o packet_parser.o packet_to_string.o symbols_linux.o symbols_freebsd.o symbols_openbsd.o symbols_netbsd.o gre_packet.o icmp_packet.o ip_packet.o tcp_packet.o udp_packet.o mpls_packet.o run.o run_command.o run_packet.o run_system_call.o script.o socket.o system.o tcp_options.o tcp_options_iterator.o tcp_options_to_string.o logging.o types.o lexer.o parser.o fmemopen.o open_memstream.o link_layer.o wire_conn.o wire_protocol.o wire_client.o wire_client_netdev.o wire_server.o wire_server_netdev.o utils.o mptcp.o queue/queue.o  -lpthread -lrt -lcrypto -ldl -lz
/usr/bin/ld: tcp_packet.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: run.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: run_packet.o:(.bss+0x20): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: run_packet.o:(.bss+0x1880): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: run_system_call.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: run_system_call.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: tcp_options.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: tcp_options_iterator.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: tcp_options_iterator.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: tcp_options_to_string.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: tcp_options_to_string.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: lexer.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: parser.o:(.bss+0xa0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: parser.o:(.bss+0x1900): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: utils.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: utils.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
/usr/bin/ld: mptcp.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
/usr/bin/ld: mptcp.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile.common:37: packetdrill] Error 1
```

I didn't investigate more so far.

2023-01-19 11:27 UTC, matttbe commented
OK, I had to backport:

- https://github.com/google/packetdrill/pull/45
- https://github.com/multipath-tcp/packetdrill/pull/36

This fixes the linker issues but not all the other warnings :)

I can add them to the list

2023-01-19 11:42 UTC, matttbe commented
@cpaasch mmh, I don't have the rights to push on your branch :-/

```
ERROR: Permission to cpaasch/packetdrill_mptcp.git denied to matttbe.
fatal: Could not read from remote repository.
```

But in theory, I should have write access as I can see the message:

> Add more commits by pushing to the [mptcp_v0.96](https://github.com/cpaasch/packetdrill_mptcp/tree/mptcp_v0.96) branch on [cpaasch/packetdrill_mptcp](https://github.com/cpaasch/packetdrill_mptcp).

I then created https://github.com/cpaasch/packetdrill_mptcp/pull/2

Feel free to

```
git fetch git@github.com:matttbe/packetdrill_mptcp.git mptcp_v0.96 && git reset --hard FETCH_HEAD
```

2023-01-19 14:24 UTC, matttbe commented
@cpaasch when running the tests, it stopped with:

```
./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
```

Then I recreated the VM and now when it tries to run a test, I have:

```
# ./run_test.sh 
net.mptcp.mptcp_path_manager = default
net.mptcp.mptcp_version = 0
net.ipv4.tcp_no_metrics_save = 1
Running ./mp_capable/mp_capable_bind_no_cs_cookies.pkt ...
net.mptcp.mptcp_checksum = 0
net.ipv4.tcp_syncookies = 2
assertion l4_bytes > 0 failed at packet_checksum.c line 79
```

Any idea? :-)

2023-01-19 14:49 UTC, matttbe commented
@cpaasch FYI, I just pushed the script I used to do the tests on my side: https://github.com/multipath-tcp/mptcp-scripts/tree/master/testing

In short, if you or someone else wants to setup the same environment, make sure docker is installed, then get the `virtme.sh` script from this repo and launch it from your kernel source dir :-)
New files will only be created in a new `.virtme` dir.

Note that the same docker image is used by the public CI to run upstream tests. Here it is a wrapper on top of it to be able to run it in the fork kernel.

2023-01-19 18:23 UTC, cpaasch commented
> @cpaasch when running the tests, it stopped with:
> 
> ```
> ./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
> ```

I guess that this is due to your `tcp_wmem` setting.

Mine is:
```
$ cat /proc/sys/net/ipv4/tcp_wmem
4096    16384   4194304
```

So, we probably should set this.

> 
> Then I recreated the VM and now when it tries to run a test, I have:
> 
> ```
> # ./run_test.sh 
> net.mptcp.mptcp_path_manager = default
> net.mptcp.mptcp_version = 0
> net.ipv4.tcp_no_metrics_save = 1
> Running ./mp_capable/mp_capable_bind_no_cs_cookies.pkt ...
> net.mptcp.mptcp_checksum = 0
> net.ipv4.tcp_syncookies = 2
> assertion l4_bytes > 0 failed at packet_checksum.c line 79
> ```
> 
> Any idea? :-)

That's weird... not sure what this is...

2023-01-19 18:23 UTC, cpaasch commented on gtests/net/packetdrill/ip.h
> +#define IP_ECN_MASK 7
Who knows... ;-) I think it was to do the TOS-tests (?)

2023-01-19 18:26 UTC, cpaasch commented
> > > It looks good to me!
> > > I didn't run all the tests yet. I don't know if it makes sense for me to do so because I'm probably sure I will have issues with the timing stuff, not have the same kind of test machine as you but I will check if I can.
> > 
> > 
> > All tests pass for me. Regarding the timing, overall it would be good to get rid of `--tolerance_usecs` across the tests and rather use targeted ranges for those packets/events that have variance. That is in my experience the best approach.
> 
> When using a public CI, especially with the debug kernel config, the execution is quite/very slow.

It is slow, yes. But are we missing the deadlines of the timers? Can you give some examples of failures in the CI ? (I got quite some experience running packetdrill on extremely CPU-constrained devices ;-) )

> For the moment, I don't see how we can increase the default time "globally" for the CI.

One thing that one could do (unless we add proper time-ranges in all the scripts) is to detect at runtime if the test is running on the CI. And based on that increase the tolerance. Is there anything we could check at runtime to see if we are in the CI?

>  Except modifying `tolerance_usecs` (or `tolerance_percent`, new option from upstream) in config.c or modifying `run_all.py`.
> 
> > > Anyway, we can already merge, not waiting for these results if you prefer.
> > 
> > 
> > Yes, good to merge IMO.
> 
> I wanted to do some tests before but I was not able to compile the new version, maybe because I use GCC 11?
> 
> I have a lot of warnings (`-Wunused-result`, `-Waddress-of-packed-member`, `-Wformat=`, `-Wdeprecated-declarations`, `-Wstrict-aliasing`, `-Wparentheses`, `-Wmisleading-indentation`) and then the linker fails:
> 
> ```
> cc -o packetdrill packetdrill.o checksum.o code.o config.o hash.o hash_map.o ip_address.o ip_prefix.o netdev.o net_utils.o packet.o packet_socket_linux.o packet_socket_pcap.o packet_checksum.o packet_parser.o packet_to_string.o symbols_linux.o symbols_freebsd.o symbols_openbsd.o symbols_netbsd.o gre_packet.o icmp_packet.o ip_packet.o tcp_packet.o udp_packet.o mpls_packet.o run.o run_command.o run_packet.o run_system_call.o script.o socket.o system.o tcp_options.o tcp_options_iterator.o tcp_options_to_string.o logging.o types.o lexer.o parser.o fmemopen.o open_memstream.o link_layer.o wire_conn.o wire_protocol.o wire_client.o wire_client_netdev.o wire_server.o wire_server_netdev.o utils.o mptcp.o queue/queue.o  -lpthread -lrt -lcrypto -ldl -lz
> /usr/bin/ld: tcp_packet.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: run.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: run_packet.o:(.bss+0x20): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: run_packet.o:(.bss+0x1880): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: run_system_call.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: run_system_call.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: tcp_options.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: tcp_options_iterator.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: tcp_options_iterator.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: tcp_options_to_string.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: tcp_options_to_string.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: lexer.o:(.bss+0x0): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: parser.o:(.bss+0xa0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: parser.o:(.bss+0x1900): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: utils.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: utils.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> /usr/bin/ld: mptcp.o:(.bss+0x0): multiple definition of `mp_state'; run.o:(.bss+0x0): first defined here
> /usr/bin/ld: mptcp.o:(.bss+0x1860): multiple definition of `tcp_option'; packet_to_string.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status
> make: *** [Makefile.common:37: packetdrill] Error 1
> ```
> 
> I didn't investigate more so far.

2023-01-20 14:17 UTC, matttbe commented
> > @cpaasch when running the tests, it stopped with:
> > ```
> > ./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
> > ```
> 
> I guess that this is due to your `tcp_wmem` setting.
> 
> Mine is:
> 
> ```
> $ cat /proc/sys/net/ipv4/tcp_wmem
> 4096    16384   4194304
> ```
> 
> So, we probably should set this.

Indeed, it would be better. But I had the same on my side:

```
$ cat /proc/sys/net/ipv4/tcp_wmem
4096    16384   4194304
```

I restarted the test VM but I didn't change the settings.

> > Then I recreated the VM and now when it tries to run a test, I have:
> > ```
> > # ./run_test.sh 
> > net.mptcp.mptcp_path_manager = default
> > net.mptcp.mptcp_version = 0
> > net.ipv4.tcp_no_metrics_save = 1
> > Running ./mp_capable/mp_capable_bind_no_cs_cookies.pkt ...
> > net.mptcp.mptcp_checksum = 0
> > net.ipv4.tcp_syncookies = 2
> > assertion l4_bytes > 0 failed at packet_checksum.c line 79
> > ```
> >   
> > Any idea? :-)
> 
> That's weird... not sure what this is...

I managed to fix the issue by... recompiling packetdrill... https://github.com/multipath-tcp/mptcp-scripts/commit/942196b3d6650716555afdfd324503c4c56793b5

2023-01-20 14:30 UTC, matttbe commented
> > > > It looks good to me!
> > > > I didn't run all the tests yet. I don't know if it makes sense for me to do so because I'm probably sure I will have issues with the timing stuff, not have the same kind of test machine as you but I will check if I can.
> > > 
> > > 
> > > All tests pass for me. Regarding the timing, overall it would be good to get rid of `--tolerance_usecs` across the tests and rather use targeted ranges for those packets/events that have variance. That is in my experience the best approach.
> > 
> > 
> > When using a public CI, especially with the debug kernel config, the execution is quite/very slow.
> 
> It is slow, yes. But are we missing the deadlines of the timers? Can you give some examples of failures in the CI ? (I got quite some experience running packetdrill on extremely CPU-constrained devices ;-) )

The hardest case I have in mind is the one related to this PR where we try to validate the ADD_ADDR retransmissions happening after one second: https://github.com/multipath-tcp/packetdrill/pull/98

If we inject packets in between, we have packets happening a few seconds **before** the expected time.

Even after that, I had to increase the tolerances. Maybe this case in the PR is an exception and I guess the best is to add more tolerance only for specific packets with `X~Y` time?

> > For the moment, I don't see how we can increase the default time "globally" for the CI.
> 
> One thing that one could do (unless we add proper time-ranges in all the scripts) is to detect at runtime if the test is running on the CI. And based on that increase the tolerance. Is there anything we could check at runtime to see if we are in the CI?

When preparing the environment, the CI can do some modifications.
With the upstream kernel, the tolerances at the beginning of the files are modified:

https://github.com/multipath-tcp/mptcp-upstream-virtme-docker/blob/ac49458340bb8e9493d6d47adca8a0010bce4f24/entrypoint.sh#L413-L434

- times 10 when using a debug kernel config
- times 4 otherwise

But we could also modify `run_all.py` or `config.c` files.

We can also detect at run time if we are using some debug kernel config, e.g.:

https://github.com/multipath-tcp/mptcp_net-next/blob/36b9e256af31c7c90dff03d800676790f8eac1f5/tools/testing/selftests/net/mptcp/simult_flows.sh#L111-L119

2023-01-20 14:33 UTC, matttbe commented
> > > @cpaasch when running the tests, it stopped with:
> > > ```
> > > ./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
> > > ```
> > 
> > 
> > I guess that this is due to your `tcp_wmem` setting.
> > Mine is:
> > ```
> > $ cat /proc/sys/net/ipv4/tcp_wmem
> > 4096    16384   4194304
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, we probably should set this.
> 
> Indeed, it would be better. But I had the same on my side:
> 
> ```
> $ cat /proc/sys/net/ipv4/tcp_wmem
> 4096    16384   4194304
> ```
> 
> I restarted the test VM but I didn't change the settings.

I manage to reproduce it:

```
(...)
Running ./mp_fastclose/04-client_rd_rst_ack_rto_fastclose.pkt ...
net.ipv4.tcp_fastopen = 0
net.ipv4.tcp_retries2 = 2
net.ipv4.tcp_retries2 = 15
Running ipv4-mapped
net.ipv4.tcp_fastopen = 0
net.ipv4.tcp_retries2 = 2
net.ipv4.tcp_retries2 = 15
Running ipv6
net.ipv4.tcp_fastopen = 0
net.ipv4.tcp_retries2 = 2
net.ipv4.tcp_retries2 = 15
Running ./dss/datafin_splitted.pkt ...
Running ipv4-mapped
Running ipv6
Running ./dss/05_meta_retransmit_new_subflow.pkt ...
net.mptcp.mptcp_checksum = 0
./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# cat /proc/sys/net/ipv4/tcp_wmem 
4096    16384   4194304
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# packetdrill ./dss/05_meta_retransmit_new_subflow.pkt
net.mptcp.mptcp_checksum = 0
./dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
```

2023-01-25 14:06 UTC, matttbe commented
@cpaasch I applied the debug patch you asked me to apply:

```diff
diff --git a/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt b/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
index a3fbee6..b781d0e 100644
--- a/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
+++ b/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
@@ -3,6 +3,8 @@
 --tolerance_usecs=10000
 +0     `sysctl -w net.mptcp.mptcp_checksum=0`
 
++0      `ip --details link show tun0`
+
 +0     socket(..., SOCK_STREAM, IPPROTO_TCP) = 3
 +0     setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
 +0     fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0
@@ -20,6 +22,8 @@
 +0     accept(3, ..., ...) = 4
 +0     fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK) = 0
 
++0 getsockopt(4, SOL_SOCKET, SO_SNDBUF, [46080], [4]) = 0
+
 +0     write(4, ..., 5000) = 5000
 +0     > P. 1:5001(5000) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
 
@@ -30,12 +34,17 @@
 +0     > P. 4321:5001(680) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
 +0     < . 1:1(0) ack 2001 win 4242 <dss dack4=1> sock(4)
 
++0 getsockopt(4, SOL_SOCKET, SO_SNDBUF, [46080], [4]) = 0
+
 +0.2   > . 2001:3441(1440) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
 
 +0     write(4, ..., 100000) = 64800
 
+
 +0.4   > . 2001:3441(1440) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
 
++0 getsockopt(4, SOL_SOCKET, SO_SNDBUF, [46080], [4]) = 0
+
 +0.1   < S 0:0(0) win 32792 <mss 1460,sackOK,nop,nop,nop,wscale 7,mp_join_syn backup=0 address_id=0 token=sha1_32(key_b)> sock(5)
 +0     > S. 0:0(0) ack 1 win 64800 <mss 1460,nop,nop,sackOK,nop,wscale 7, mp_join_syn_ack backup=0 address_id=0 sender_hmac=trunc_l64_hmac(key_b key_a) > sock(5)
 +0.1   < . 1:1(0) ack 1 win 32792 <mp_join_ack sender_hmac=full_160_hmac(key_a key_b)> sock(5)
```

It looks like I don't have the same `SNDBUF` than you:

```
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# packetdrill dss/05_meta_retransmit_new_subflow.pkt 
net.mptcp.mptcp_checksum = 0
5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 500
    link/none  promiscuity 0 minmtu 68 maxmtu 65535 
    tun type tun pi off vnet_hdr on persist off addrgenmode random numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
dss/05_meta_retransmit_new_subflow.pkt:25: runtime error in getsockopt call: Bad getsockopt optval: expected: 46080 actual: 87040
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# sysctl net.ipv4.tcp_wmem
net.ipv4.tcp_wmem = 4096        16384   4194304
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# sysctl net.ipv4.tcp_mem
net.ipv4.tcp_mem = 23691        31590   47382
```

I'm surprise the buffer is larger on my side (87040 vs 46080).

2023-01-25 23:08 UTC, cpaasch commented
Looks like `tcp_sndbuf_expand` computes the sndbuf overhead based on a number of factors. Like `sizeof(struct sk_buff)` (depends on Kconfig) and `SKB_DATA_ALIGN` (depends on the arch).

Also, if you are running BBR, `ca_ops->sndbuf_expand` will expand the sndbuf further.

So, some of these things are machine/kconfig dependent. Are you using BBR ?

2023-01-26 09:43 UTC, matttbe commented
> Looks like `tcp_sndbuf_expand` computes the sndbuf overhead based on a number of factors. Like `sizeof(struct sk_buff)` (depends on Kconfig) and `SKB_DATA_ALIGN` (depends on the arch).

Thank you for having looked and for sharing this pointer!

It is strange there is still a big difference, no?

With this patch:

```diff
diff --git a/net/ipv4/tcp_input.c b/net/ipv4/tcp_input.c
index b4612a5969b4..00679de9ff64 100644
--- a/net/ipv4/tcp_input.c
+++ b/net/ipv4/tcp_input.c
@@ -343,6 +343,8 @@ static void tcp_sndbuf_expand(struct sock *sk)
        sndmem = ca_ops->sndbuf_expand ? ca_ops->sndbuf_expand(sk) : 2;
        sndmem *= nr_segs * per_mss;
 
+       pr_info("matttbe: mss_clamp:%u, mss_cache:%u, TCP_MAX_HEADER:%d, LL_MAX_HEADER:%d, MAX_HEADER:%d, skb_shared_info:%lu, skb_buff:%lu, ca:%d, nr_segs:%u, permss:%d, sndmem:%d, sk_sndbuf:%d, tcp_wmem:%d\n", tp->rx_opt.mss_clamp, tp->mss_cache, MAX_TCP_HEADER, LL_MAX_HEADER, MAX_HEADER, SKB_DATA_ALIGN(sizeof(struct skb_shared_info)), SKB_DATA_ALIGN(sizeof(struct sk_buff)), ca_ops->sndbuf_expand ? ca_ops->sndbuf_expand(sk) : 2, nr_segs, per_mss, sndmem, sk->sk_sndbuf, sock_net(sk)->ipv4.sysctl_tcp_wmem[2]);
+
        /* MPTCP: after this sndmem is the new contribution of the
         * current subflow to the aggregated sndbuf */
        if (sk->sk_sndbuf < sndmem) {
```

(for sk_buff, I have NF_CONNTRACK, SKB_EXTENSIONS, IPV6_NDISC_NODETYPE, NET_CLS_ACT, NET_SCHED, NET_RX_BUSY_POLL, XPS, NETWORK_SECMARK and XFRM, but not NET_SWITCHDEV, NET_REDIRECT, TLS_DEVICE, BRIDGE_NETFILTER and NET_TC_SKB_EXT)

I got:

```
root@(none):/opt/packetdrill/gtests/net/packetdrill/examples/mptcp# packetdrill dss/05_meta_retransmit_new_subflow.pkt
net.mptcp.mptcp_checksum = 0
[   56.676778] TCP: matttbe: mss_clamp:1460, mss_cache:1440, TCP_MAX_HEADER:320, LL_MAX_HEADER:96, MAX_HEADER:144, skb_shared_info:320, skb_buff:256, ca:2, nr_segs:10, permss:4352, sndmem:87040, sk_sndbuf:16384, tcp_wmem:4194304
dss/05_meta_retransmit_new_subflow.pkt:35: runtime error in write call: Expected result 64800 but got 100000 with errno 2 (No such file or directory)
```

> Also, if you are running BBR, `ca_ops->sndbuf_expand` will expand the sndbuf further.
> 
> So, some of these things are machine/kconfig dependent. Are you using BBR ?

No, BBR is not even compiled in the VM, Cubic is the default one.

2023-01-30 18:22 UTC, cpaasch commented
Your TCP_MAX_HEADER is slightly higher than mine due to the kernel-config. That causes per_mss to be significantly bigger because of the roundup. One way to fix this would be to have a lower mss. That way per_mss will not be too high and roundup will keep things low. Let me try that.

2023-01-30 18:32 UTC, cpaasch commented
Can you try this here:

```
$ git diff
diff --git a/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt b/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
index a3fbee6c4f25..de165f129750 100644
--- a/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
+++ b/gtests/net/packetdrill/examples/mptcp/dss/05_meta_retransmit_new_subflow.pkt
@@ -14,7 +14,7 @@
 +0     bind(5, {sa_family = AF_INET, sin_port = htons(13001), sin_addr = inet_addr("192.168.0.1")}, ...) = 0
 +0     listen(5,1) = 0

-+0     < S 0:0(0) win 32792 <mss 1460,sackOK,nop,nop,nop,wscale 7,mp_capable_no_cs key_a> sock(3)
++0     < S 0:0(0) win 32792 <mss 1400,sackOK,nop,nop,nop,wscale 7,mp_capable_no_cs key_a> sock(3)
 +0     > S. 0:0(0) ack 1 win 64800 <mss 1460,nop,nop,sackOK,nop,wscale 7,mp_capable_no_cs key_b> sock(3)
 +0     < . 1:1(0) ack 1 win 257 <mp_capable_no_cs key_a key_b> sock(3)
 +0     accept(3, ..., ...) = 4
@@ -27,14 +27,15 @@
 /* That way reinjection won't trigger on this one and we have to go through the meta-retransmit timer */

 +0     < . 1:1(0) ack 1 win 4242 <dss dack4=1, sack 1001:2001, nop, nop> sock(4)
-+0     > P. 4321:5001(680) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
++0     > P. 4141:5001(860) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
 +0     < . 1:1(0) ack 2001 win 4242 <dss dack4=1> sock(4)

-+0.2   > . 2001:3441(1440) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
++0.2   > . 2001:3381(1380) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)

-+0     write(4, ..., 100000) = 64800
++0     write(4, ..., 100000) = 64860

-+0.4   > . 2001:3441(1440) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)
+
++0.4   > . 2001:3381(1380) ack 1 <dss dack4 dsn4 nocs, nop, nop> sock(4)

 +0.1   < S 0:0(0) win 32792 <mss 1460,sackOK,nop,nop,nop,wscale 7,mp_join_syn backup=0 address_id=0 token=sha1_32(key_b)> sock(5)
 +0     > S. 0:0(0) ack 1 win 64800 <mss 1460,nop,nop,sackOK,nop,wscale 7, mp_join_syn_ack backup=0 address_id=0 sender_hmac=trunc_l64_hmac(key_b key_a) > sock(5)
```

2023-01-30 18:33 UTC, cpaasch commented
Reducing the mss by 60 bytes, so that per_mss does not get rounded up to 4KB but stays at 2KB.

2023-01-31 12:33 UTC, matttbe commented
@cpaasch nice, thank you. Indeed, it is better now, it passes in my test env, thanks!

2023-01-31 14:22 UTC, matttbe commented
I forgot to mention no other tests are failing :-)

2023-01-31 20:51 UTC, cpaasch commented
Thanks for testing! I pushed the updated script!

2023-01-31 20:59 UTC, matttbe commented
Thank you for the follow-up and detailed new commit! 😁
Let's merge then!

2023-01-31 21:00 UTC, merged

2023-02-01 09:29 UTC, matttbe commented
@cpaasch just in case you want to do more validations from the Virtme docker image, you might be interested by this recent modification: https://github.com/multipath-tcp/mptcp-scripts/commit/2ffdeaabcdbc8a6c7f40796c887ede1131e41e3d (it was already working with the upstream kernel but not with the fork)